### ISSUE TITLE
Intermittent spec failure in miq-benchmark_spec.rb

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-gems-pending#444]
Found on #443 https://travis-ci.org/ManageIQ/manageiq-gems-pending/jobs/570796622 (not sure how long that link will be valid for...)

```
 1) Benchmark Timeout raising within .realtime_block
     Failure/Error: raise("Completed without Timeout!?  Tip: may result from unclosed Tempfile object.")
     
     RuntimeError:
       Completed without Timeout!?  Tip: may result from unclosed Tempfile object.
     # ./spec/util/extensions/miq-benchmark_spec.rb:124:in `block (3 levels) in <top (required)>'
     # ./spec/util/extensions/miq-benchmark_spec.rb:112:in `times'
     # ./spec/util/extensions/miq-benchmark_spec.rb:112:in `block (2 levels) in <top (required)>'
```

**Comment by Fryguy** [comment]
Closing as I haven't seen this one in forever, and also the link is dead.
